# Generated by Django 5.0.3 on 2024-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='static/images/download (3).jpeg', upload_to='product_images/'),
        ),
    ]
