# Generated by Django 5.0.3 on 2024-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/download (3).jpeg/', upload_to='product_images/'),
        ),
    ]
